### ISSUE TITLE
Fully reproducible instructions?

### ISSUE THREAD

**Issue by jcrben** [SirCmpwn/mcwayface#1]
Hey, I tried following along with your blog - running Ubuntu 17.10 - but I ran into issues. First off `apt install meson` was too old (0.42). So I installed it from pip3 to get 0.44. Then I got the pkg-config error at the bottom. And I could install pkg-config, but not sure about the version (when I installed it, I got `pixman-l` missing). I think I could work through everything if I spent the time, but everyone would benefit if the steps were laid out here.

I'm building my environment with packer (https://gitlab.com/jcrben-play-learn/packer-desktop) and running it in virtualbox - I don't mind building a different OS with packer to get it into your exact state. There's also things like nix-shell (https://compiletoi.net/share-scripts-that-have-dependencies-with-nix/).

Would you mind detailing all the steps to make it completely reproducible? I think this is particularly helpful since it's the first in your planned series.

![image](https://user-images.githubusercontent.com/5614134/36356262-803924ca-14a4-11e8-8d0d-f4641a81f32e.png)

I know you said "A good understanding of C is mandatory" - I'm primarily a web developer and haven't written C much at all since college, but I'm still interested. Hope that's alright. By the way, gave $10 to the campaign - keep up the good work!

**Comment by ddevault** [comment]
The error message tells you what you need - you're missing dependencies. This is a pretty fundamental dependency, I don't think you have your toolchain set up at all. Install `build-essential`.

**Comment by jcrben** [comment]
`build-essential` wasn't a problem (it was installed). As I mentioned above, I had already installed `pkg-config` after which it said I needed `pixman-l`, so I dug up `libpixman-1-dev/artful`. After that, it failed on the [`wlroots`](https://github.com/swaywm/wlroots) dependency. 

Which I guess I'd have to compile from source since debian hasn't packaged it, but then I go to wlroots to figure out the necessary dependencies and I find a similar issue - the dependencies are listed, but few to no versions in the meson build (https://github.com/swaywm/wlroots/blob/master/meson.build#L54).

I understand that dependency / package management isn't so simple in the C world (altho there are a bunch, e.g. the list at http://pfultz2.com/blog/2017/10/27/universal-package-manager/) and there's dozens of Linux distributions. But there's also Docker, nix, or just old-fashioned words.

And not specifying versions leads to bug reports like https://github.com/swaywm/wlroots/issues/323 and https://github.com/swaywm/wlroots/issues/126 - not to mention more subtle issues when the build doesn't fail but the business logic does... life is just far too short. Sorry if that sounds whiny, but I think the message is just too important to be shy about it for fear of offending someone.

**Comment by ddevault** [comment]
Sorry, the goal is not to teach people how to use C. It's to teach people who know C how to write Wayland compositors.
